name: terraformQA
on:
  workflow_dispatch:
    inputs:
      force_build:
        description: Force Build
        type: boolean
        default: false
        required: false
  push:
    branches:
      - develop
    paths:
      - Infraestructure/Provisioning/QAs/**
jobs:
  build:
    name: Execute Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: LOrQVz0Qy2RYdw.atlasv1.BWqetUMBolMsY0Lu1IbzC9g3ObXkhg8MNdzwvl6Kw9FpuGc6Etn7bDq825REeDIWWPI

      - name: Terraform Init
        working-directory: Infraestructure/Provisioning/QA/        
        run: |
          terraform init
          terraform validate
          terraform plan
