name: terraformQA
on:
  workflow_dispatch:
    inputs:
      force_build:
        description: Force Build
        type: boolean
        default: false
        required: false
  push:
    branches:
      - develop
    paths:
      - Infraestructure/Provisioning/QAs/**
jobs:
  build:
    name: Execute Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Terrafrom Script
        working-directory: Infraestructure/Provisioning/QA/
        run: |
          terraform init
          terraform validate
          terraform plan
##        terraform apply -auto-approve
